# fly.toml app configuration file generated for hcm201-web-app-aged-grass-7467 on 2025-09-17T18:02:13+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hcm201-web-app-aged-grass-7467'
primary_region = 'sin'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  dockerfile = 'Dockerfile'

[env]
  NEXT_TELEMETRY_DISABLED = '1'
  NODE_ENV = 'production'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '15s'
    timeout = '2s'

[[services]]
  protocol = 'tcp'
  internal_port = 3000
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
